### ISSUE TITLE
bot information changes are not displayed to me

### ISSUE THREAD

**Issue by KazamaWataru** [tamtam-chat/tamtam-bot-api#9]
Hello! I am writing a TamTam Bot. When I set the robot avatar via tt.me/PrimeBot, I found that this does not work for my client (both android and desktop) but the modification is displayed on the tt.me/username link! What went wrong? I tried "remove contact" and "remove chat", but these don't work ...

**Comment by achuprin** [comment]
Hello. There is a bug on the server side. Avatar is cached on clients and isn’t updated when primebot changes it. We will fix it soon.
